"""empty message

Revision ID: 5cf8fb0d5cf9
Revises: ed657e16ce20
Create Date: 2017-07-20 14:44:46.841254

"""

# revision identifiers, used by Alembic.
revision = '5cf8fb0d5cf9'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    sa.UniqueConstraint('email', name=u'user_email_key')
    )
    ### end Alembic commands ###
